export const countries = [
  "Botswana",
  "Tonga",
  "Greece",
  "Marshall Islands",
  "Belarus",
  "Republic of the Congo",
  "Tanzania",
  "Liechtenstein",
  "Sint Maarten",
  "Bosnia and Herzegovina",
  "Bahrain",
  "Kenya",
  "Estonia",
  "Qatar",
  "Poland",
  "Moldova",
  "Jordan",
  "Tunisia",
  "Paraguay",
  "Malaysia",
  "Cameroon",
  "Solomon Islands",
  "Mongolia",
  "Vanuatu",
  "Nepal",
  "Guam",
  "Lebanon",
  "Ivory Coast",
  "Ecuador",
  "Palau",
  "Kyrgyzstan",
  "Egypt",
  "North Korea",
  "Senegal",
  "British Virgin Islands",
  "Costa Rica",
  "Guatemala",
  "China",
  "Kazakhstan",
  "Cape Verde",
  "Vatican City",
  "Bhutan",
  "Colombia",
  "Grenada",
  "Northern Mariana Islands",
  "Papua New Guinea",
  "Antarctica",
  "South Africa",
  "Guinea",
  "Hong Kong",
  "Chad",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Honduras",
  "Montenegro",
  "Morocco",
  "Nicaragua",
  "Cayman Islands",
  "Luxembourg",
  "Guyana",
  "Bulgaria",
  "Ghana",
  "Finland",
  "Seychelles",
  "United States Virgin Islands",
  "Ethiopia",
  "Mauritania",
  "Iceland",
  "Réunion",
  "Tajikistan",
  "Cuba",
  "Somalia",
  "Switzerland",
  "Christmas Island",
  "Martinique",
  "Australia",
  "Benin",
  "Laos",
  "Sudan",
  "Libya",
  "Mali",
  "Peru",
  "Hungary",
  "Bermuda",
  "Fiji",
  "Netherlands",
  "Nigeria",
  "Portugal",
  "India",
  "South Georgia",
  "Lesotho",
  "Zambia",
  "Tokelau",
  "Gambia",
  "Sierra Leone",
  "Kiribati",
  "Norway",
  "Ireland",
  "Greenland",
  "British Indian Ocean Territory",
  "Mozambique",
  "Panama",
  "Ukraine",
  "Uruguay",
  "Aruba",
  "Iran",
  "Isle of Man",
  "Åland Islands",
  "Saudi Arabia",
  "Djibouti",
  "Italy",
  "Canada",
  "Jamaica",
  "Niger",
  "Afghanistan",
  "Croatia",
  "Latvia",
  "Samoa",
  "Curaçao",
  "Cyprus",
  "Madagascar",
  "Uzbekistan",
  "Macau",
  "Micronesia",
  "Maldives",
  "Slovenia",
  "Andorra",
  "Eritrea",
  "Guinea-Bissau",
  "Kuwait",
  "Gabon",
  "Yemen",
  "Cocos (Keeling) Islands",
  "Timor-Leste",
  "Slovakia",
  "Rwanda",
  "Antigua and Barbuda",
  "Togo",
  "Syria",
  "Guadeloupe",
  "Turkmenistan",
  "Sri Lanka",
  "United States",
  "Argentina",
  "South Sudan",
  "Palestine",
  "Georgia",
  "Japan",
  "Sweden",
  "Chile",
  "Saint Kitts and Nevis",
  "Denmark",
  "United States Minor Outlying Islands",
  "American Samoa",
  "Anguilla",
  "Philippines",
  "Bolivia",
  "São Tomé and Príncipe",
  "Montserrat",
  "Myanmar",
  "Niue",
  "Israel",
  "Heard Island and McDonald Islands",
  "Comoros",
  "Saint Vincent and the Grenadines",
  "Vietnam",
  "Caribbean Netherlands",
  "Jersey",
  "Falkland Islands",
  "Armenia",
  "Kosovo",
  "Bouvet Island",
  "Venezuela",
  "Belgium",
  "Burkina Faso",
  "Algeria",
  "France",
  "Saint Pierre and Miquelon",
  "Pakistan",
  "El Salvador",
  "North Macedonia",
  "Brunei",
  "Central African Republic",
  "Uganda",
  "Wallis and Futuna",
  "Germany",
  "Taiwan",
  "United Arab Emirates",
  "Namibia",
  "Monaco",
  "Malawi",
  "Azerbaijan",
  "Mexico",
  "Iraq",
  "Cambodia",
  "Tuvalu",
  "Cook Islands",
  "Haiti",
  "Belize",
  "French Guiana",
  "DR Congo",
  "Equatorial Guinea",
  "Mauritius",
  "Austria",
  "Spain",
  "Russia",
  "Zimbabwe",
  "Singapore",
  "Czechia",
  "Faroe Islands",
  "Oman",
  "French Southern and Antarctic Lands",
  "Burundi",
  "Western Sahara",
  "Mayotte",
  "Puerto Rico",
  "San Marino",
  "Turks and Caicos Islands",
  "Malta",
  "Nauru",
  "Saint Martin",
  "French Polynesia",
  "New Zealand",
  "Serbia",
  "Trinidad and Tobago",
  "Saint Barthélemy",
  "Pitcairn Islands",
  "Norfolk Island",
  "Barbados",
  "South Korea",
  "Bangladesh",
  "Dominican Republic",
  "Turkey",
  "Indonesia",
  "Liberia",
  "Guernsey",
  "Suriname",
  "Albania",
  "Dominica",
  "Thailand",
  "United Kingdom",
  "New Caledonia",
  "Romania",
  "Gibraltar",
  "Svalbard and Jan Mayen",
  "Angola",
  "Bahamas",
  "Eswatini",
  "Brazil",
  "Lithuania",
  "Saint Lucia",
];
export const languages = [
  { code: "en", name: "English" },
  { code: "ar", name: "Arabic" },
  { code: "fr", name: "French" },
  { code: "es", name: "Spanish" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "pt", name: "Portuguese" },
  { code: "tr", name: "Turkish" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengali" },
  { code: "ur", name: "Urdu" },
  { code: "fa", name: "Persian" },
] as const;

// Trip names and place names are defined below after the main places list

export const AllPlacesName = [
  "Abu Mena Archaeological Site",
  "Al-Shatby Necropolis",
  "Alexandria National Museum",
  "Anfushi Tombs",
  "Greco-Roman Museum",
  "Kom El-Dikka (Roman Theatre)",
  "Kom El-Shoqafa Catacombs",
  "Mostafa Kamel Tombs",
  "Pompey's Pillar",
  "Qaitbay Citadel",
  "Qaitbay Citadel (Alexandria)",
  "Roman Theater",
  "Royal Jewelry Museum",
  "Sunken Monuments of the Eastern Harbor",
  "Abu Simbel Temple",
  "Abu Simbel Temples",
  "Amada Temples",
  "Crocodile Museum (Kom Ombo)",
  "Edfu Temple",
  "El-Kab",
  "Elephantine Island",
  "Gebel Silsila",
  "Isis Temple",
  "Kalabsha Temples",
  "Kom Ombo Temple",
  "Nubian Museum",
  "Philae Temple",
  "Philae Temples",
  "Philae Temples Panorama",
  "Qubbet El-Hawa",
  "Seheil Island",
  "Sun Festival (Abu Simbel Temples October 22 & February 22)",
  "Unfinished Obelisk",
  "Vehicle Tickets for Abu Simbel Temples",
  "Vehicle Tickets for Kom Ombo Temple",
  "Wadi El-Seboua Temples",
  "Bahariya Oasis Archaeological Area",
  "Ahmad Ibn Tulun Mosque",
  "Al-Darb Al-Ahmar Tourist Path",
  "Al-Ghouri Complex (Dome Sabil and House)",
  "Al-Ghouri Wekala",
  "Al-Harawi House",
  "Al-Mawlawi Tekkiyeh",
  "Al-Rifa'i Mosque",
  "Al-Rifa’i Mosque",
  "Al-Sitt Wasila House",
  "Al-Zahir Baybars Mosque",
  "Ali Labib House",
  "Amr Ibn Al-As Mosque",
  "Audio Guide (for Groups) - The Egyptian Museum",
  "Baron Palace",
  "Ben Ezra Synagogue",
  "Cairo Airport Museum 2",
  "Cairo Airport Museum 3",
  "Church of Abu Serga",
  "Egyptian Museum",
  "Farouk Corner Museum",
  "Gamal El-Din Al-Dhahabi House",
  "Gayer-Anderson Museum",
  "Islamic Art Museum",
  "Manial Palace",
  "Museum of Islamic Art",
  "Nafisa Al-Bayda Sabil-Kuttab",
  "National Museum of Egyptian Civilization",
  "Nileometer",
  "Prince Mohammed Ali Palace (Al-Manial Palace Museum)",
  "Prince Taz Palace",
  "Qaytbay Sabil-Kuttab (Salah Al-Din Street)",
  "Royal Carriages Museum",
  "Royal Family Tombs",
  "Salah El-Din Citadel",
  "Senusret I Obelisk (Matareya)",
  "Sultan Hassan Mosque",
  "The Coptic Museum",
  "The Egyptian Museum (Tahrir Square)",
  "The Hanging Church",
  "Tree of the Virgin Mary",
  "Esna Temple",
  "Hawara Pyramid",
  "Karanis Archaeological Area",
  "Kom Oshim Museum",
  "Lahun Pyramid",
  "Medinet Madi Temple",
  "Meidum Pyramid",
  "Qarun Palace",
  "Sultan Zawiya",
  "Virgin Mary Monastery",
  "Comprehensive Ticket for All Saqqara Tombs",
  "Dahshur Archaeological Area",
  "Giza Pyramids",
  "Khufu Pyramid (Interior Visit)",
  "Menkaure Pyramid",
  "Meresankh III Tomb",
  "Mit Rahina (Memphis) Archaeological Area",
  "Nobles' Tombs and New Kingdom Tombs (Tombs of Horemheb and Bubastites)",
  "Saqqara Necropolis",
  "Sphinx",
  "Step Pyramid of Djoser (Southern Entrance)",
  "The Great Sphinx",
  "The Serapeum",
  "The Southern Tomb",
  "Tomb of Mereruka",
  "Vehicle Tickets for Mit Rahina Archaeological Area",
  "Vehicle Tickets for Saqqara Archaeological Area",
  "Workers' Tombs",
  "Ismailia Museum",
  "Kafr El-Sheikh Museum",
  "Al-Asasif Necropolis",
  "Anba Samaan Monastery",
  "Audio Guide - Luxor Museum",
  "Ay Tomb",
  "Baba Tomb",
  "Carter House & Tutankhamun's Replica Tomb",
  "Colossi of Memnon",
  "Deir El-Bahari (Hatshepsut Temple)",
  "Deir El-Medina",
  "El-Asasif Necropolis",
  "El-Khokha Tombs",
  "Isis Temple (Deir Shalwit)",
  "Karnak Temple",
  "Karnak Temples",
  "Luxor Museum",
  "Luxor Temple",
  "Medinet Habu Temple",
  "Menna & Nakht Tombs",
  "Merenptah Temple",
  "Mummification Museum",
  "Mut Temple (Karnak Complex)",
  "Nefertari Tomb",
  "Pashedu Tomb",
  "Qurna Merai Necropolis",
  "Ramesseum Temple",
  "Ramose Tomb",
  "Ramses V & VI Tomb",
  "Rekhmire & Sennefer Tombs",
  "Seti I Temple",
  "Seti I Tomb",
  "Sheikh Abd El-Qurna North Tombs",
  "Sheikh Abd El-Qurna South Tombs",
  "Tutankhamun's Tomb",
  "Userhat & Khaemwaset Tombs",
  "Valley of the Kings",
  "Valley of the Queens",
  "Cave of Rommel Museum",
  "Matrouh Museum",
  "Al-Muharraq Monastery",
  "Beni Hassan Tombs",
  "El-Hammamiya Tombs",
  "Fraser Tombs",
  "Mallawi Museum",
  "Mir Tombs",
  "Mizawqa Tombs",
  "Royal Tomb of Akhenaten",
  "Tell El-Amarna",
  "Tuna El-Gebel",
  "Vehicle Tickets for Tuna El-Gebel Archaeological Area",
  "Al-Bagawat Necropolis",
  "Al-Dabba and Ain Aseel Forts",
  "Al-Ghweita Temple",
  "Al-Zayan Temple",
  "Azbet Bashandi Archaeological Area",
  "Deir El-Hagar Temple",
  "Dush Temple",
  "Hibis Temple",
  "New Valley Museum",
  "Qasr El-Miqyass (Qasr El-Ghueita)",
  "Al-Jadawi Wekala",
  "Al-Ma'ala Tombs",
  "Dendera Temple",
  "Dendera Temple Crypts",
  "Dendera Temple Panorama",
  "El-Tod Temple",
  "Qaitbay Citadel (Rosetta)",
  "Rashid (Rosetta) Monuments",
  "Anba Antonius Monastery",
  "Anba Paula Monastery",
  "El-Quseir Citadel",
  "Hurghada Museum",
  "San El-Hagar Archaeological Site",
  "Tell Basta Archaeological Site",
  "Tell Basta Museum",
  "Vehicle Tickets for Tell Basta Archaeological Area",
  "Salah El-Din Citadel (Taba)",
  "Sharm El-Sheikh Museum",
  "St. Catherine's Monastery",
  "Temple of Hathor (Dendera Crypts)",
  "Mountain of the Dead Tombs (Siwa)",
  "Temple of the Oracle (Siwa)",
  "Al-Hawawish Tombs",
  "Merit Amun Temple",
  "Prince Youssef Kamal Palace",
  "Seti I Temple (Abydos)",
  "Sheikh Hamad Area",
  "Shunet El-Zebib and Kom El-Sultan",
  "Sohag National Museum",
  "The Red Monastery",
  "The White Monastery",
  "Suez National Museum",
  "Tanta Museum",
  "Anba Bishoy Monastery",
  "Anba Makarios Monastery",
  "Baramus Monastery",
  "El-Suryan Monastery",
] as const;

export const AllTripsName = [
  "Ancient Echoes",
  "Aswan Explorations",
  "Delta Expeditions",
  "Desert Trails",
  "Giza Quest",
  "Luxor Ventures",
  "Necropolis Trails",
  "Saqqara Secrets",
  "Upper Egypt Odyssey",
  "Desert Sanctuaries",
  "Mediterranean Shores",
  "Red Sea Retreat",
  "Ancient Cities",
  "Aswan Horizons",
  "Cairo Chronicles",
  "Coastal Chronicles",
  "Islamic Heritage",
  "Luxor Legends",
  "Nile Temples",
  "Oasis Odyssey",
  "Pyramid Pathways",
  "Rosetta Routes",
  "Sacred Sites",
  "Theban Tombs",
  "Alexandria Quest",
  "Cairo Splendor",
  "Cultural Capitals",
  "Delta Discovery",
  "Regional Riches",
  "Urban Heritage",
  "Desert Serenity",
  "Spiritual Nile",
] as const;
export const languageCodes = languages.map((lang) => lang.code) as [
  string,
  ...string[]
];
