export const countries = [
  "Botswana",
  "Tonga",
  "Greece",
  "Marshall Islands",
  "Belarus",
  "Republic of the Congo",
  "Tanzania",
  "Liechtenstein",
  "Sint Maarten",
  "Bosnia and Herzegovina",
  "Bahrain",
  "Kenya",
  "Estonia",
  "Qatar",
  "Poland",
  "Moldova",
  "Jordan",
  "Tunisia",
  "Paraguay",
  "Malaysia",
  "Cameroon",
  "Solomon Islands",
  "Mongolia",
  "Vanuatu",
  "Nepal",
  "Guam",
  "Lebanon",
  "Ivory Coast",
  "Ecuador",
  "Palau",
  "Kyrgyzstan",
  "Egypt",
  "North Korea",
  "Senegal",
  "British Virgin Islands",
  "Costa Rica",
  "Guatemala",
  "China",
  "Kazakhstan",
  "Cape Verde",
  "Vatican City",
  "Bhutan",
  "Colombia",
  "Grenada",
  "Northern Mariana Islands",
  "Papua New Guinea",
  "Antarctica",
  "South Africa",
  "Guinea",
  "Hong Kong",
  "Chad",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Honduras",
  "Montenegro",
  "Morocco",
  "Nicaragua",
  "Cayman Islands",
  "Luxembourg",
  "Guyana",
  "Bulgaria",
  "Ghana",
  "Finland",
  "Seychelles",
  "United States Virgin Islands",
  "Ethiopia",
  "Mauritania",
  "Iceland",
  "Réunion",
  "Tajikistan",
  "Cuba",
  "Somalia",
  "Switzerland",
  "Christmas Island",
  "Martinique",
  "Australia",
  "Benin",
  "Laos",
  "Sudan",
  "Libya",
  "Mali",
  "Peru",
  "Hungary",
  "Bermuda",
  "Fiji",
  "Netherlands",
  "Nigeria",
  "Portugal",
  "India",
  "South Georgia",
  "Lesotho",
  "Zambia",
  "Tokelau",
  "Gambia",
  "Sierra Leone",
  "Kiribati",
  "Norway",
  "Ireland",
  "Greenland",
  "British Indian Ocean Territory",
  "Mozambique",
  "Panama",
  "Ukraine",
  "Uruguay",
  "Aruba",
  "Iran",
  "Isle of Man",
  "Åland Islands",
  "Saudi Arabia",
  "Djibouti",
  "Italy",
  "Canada",
  "Jamaica",
  "Niger",
  "Afghanistan",
  "Croatia",
  "Latvia",
  "Samoa",
  "Curaçao",
  "Cyprus",
  "Madagascar",
  "Uzbekistan",
  "Macau",
  "Micronesia",
  "Maldives",
  "Slovenia",
  "Andorra",
  "Eritrea",
  "Guinea-Bissau",
  "Kuwait",
  "Gabon",
  "Yemen",
  "Cocos (Keeling) Islands",
  "Timor-Leste",
  "Slovakia",
  "Rwanda",
  "Antigua and Barbuda",
  "Togo",
  "Syria",
  "Guadeloupe",
  "Turkmenistan",
  "Sri Lanka",
  "United States",
  "Argentina",
  "South Sudan",
  "Palestine",
  "Georgia",
  "Japan",
  "Sweden",
  "Chile",
  "Saint Kitts and Nevis",
  "Denmark",
  "United States Minor Outlying Islands",
  "American Samoa",
  "Anguilla",
  "Philippines",
  "Bolivia",
  "São Tomé and Príncipe",
  "Montserrat",
  "Myanmar",
  "Niue",
  "Israel",
  "Heard Island and McDonald Islands",
  "Comoros",
  "Saint Vincent and the Grenadines",
  "Vietnam",
  "Caribbean Netherlands",
  "Jersey",
  "Falkland Islands",
  "Armenia",
  "Kosovo",
  "Bouvet Island",
  "Venezuela",
  "Belgium",
  "Burkina Faso",
  "Algeria",
  "France",
  "Saint Pierre and Miquelon",
  "Pakistan",
  "El Salvador",
  "North Macedonia",
  "Brunei",
  "Central African Republic",
  "Uganda",
  "Wallis and Futuna",
  "Germany",
  "Taiwan",
  "United Arab Emirates",
  "Namibia",
  "Monaco",
  "Malawi",
  "Azerbaijan",
  "Mexico",
  "Iraq",
  "Cambodia",
  "Tuvalu",
  "Cook Islands",
  "Haiti",
  "Belize",
  "French Guiana",
  "DR Congo",
  "Equatorial Guinea",
  "Mauritius",
  "Austria",
  "Spain",
  "Russia",
  "Zimbabwe",
  "Singapore",
  "Czechia",
  "Faroe Islands",
  "Oman",
  "French Southern and Antarctic Lands",
  "Burundi",
  "Western Sahara",
  "Mayotte",
  "Puerto Rico",
  "San Marino",
  "Turks and Caicos Islands",
  "Malta",
  "Nauru",
  "Saint Martin",
  "French Polynesia",
  "New Zealand",
  "Serbia",
  "Trinidad and Tobago",
  "Saint Barthélemy",
  "Pitcairn Islands",
  "Norfolk Island",
  "Barbados",
  "South Korea",
  "Bangladesh",
  "Dominican Republic",
  "Turkey",
  "Indonesia",
  "Liberia",
  "Guernsey",
  "Suriname",
  "Albania",
  "Dominica",
  "Thailand",
  "United Kingdom",
  "New Caledonia",
  "Romania",
  "Gibraltar",
  "Svalbard and Jan Mayen",
  "Angola",
  "Bahamas",
  "Eswatini",
  "Brazil",
  "Lithuania",
  "Saint Lucia",
];
export const languages = [
  { code: "en", name: "English" },
  { code: "ar", name: "Arabic" },
  { code: "fr", name: "French" },
  { code: "es", name: "Spanish" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "pt", name: "Portuguese" },
  { code: "tr", name: "Turkish" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengali" },
  { code: "ur", name: "Urdu" },
  { code: "fa", name: "Persian" },
];
